name: volumedeck_flutter
description: The Volumedeck SDK provides automatic volume adjustment based on GPS speed, improving the media-listening experience for users in vehicles and public transport.
version: 1.1.1
homepage: https://navideck.com
repository: https://github.com/Navideck/volumedeck_sdk_flutter
issue_tracker: https://github.com/Navideck/volumedeck_sdk_flutter/issues
documentation: https://navideck.github.io/volumedeck_sdk_flutter/doc

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^10.1.4  

flutter:
  plugin:
    platforms:
      android:
        package: com.navideck.volumedeck_flutter
        pluginClass: VolumedeckFlutterPlugin
      ios:
        pluginClass: VolumedeckFlutterPlugin
