name: volumedeck_flutter
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^10.1.4  

flutter:
  plugin:
    platforms:
      android:
        package: com.navideck.volumedeck_flutter
        pluginClass: VolumedeckFlutterPlugin
      ios:
        pluginClass: VolumedeckFlutterPlugin
