# name: Update docs

# on:
#   # push:
#   #   branches: [ main ]
#   #   paths-ignore: [ 'docs/**', 'README.md' ]
#   # pull_request:
#   #   branches: [ main ]
#   release:
#     types: [published]
#   workflow_dispatch:

# concurrency:
#   group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
#   cancel-in-progress: true

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#       with:
#         fetch-depth: 0
#     - uses: subosito/flutter-action@v2
#       with:
#         channel: 'stable'
#     - name: Generate API documentation
#       if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
#       run: dart doc
#     - uses: stefanzweifel/git-auto-commit-action@v4
#       with:
#         commit_message: Update docs